export const PRODUCT_ACTION_TYPES = {
  FETCH_PRODUCTS_START: "product/FETCH_PRODUCTS_START",
  FETCH_PRODUCT_DETAILS_START: "product/FETCH_PRODUCT_DETAILS_START",
  FETCH_PRODUCTS_SUCCESS: "product/FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCT_DETAILS_SUCCESS: "product/FETCH_PRODUCT_DETAILS_SUCCESS",
  FETCH_PRODUCTS_FAILED: "product/FETCH_PRODUCTS_FAILED",
  FETCH_PRODUCT_DETAILS_FAILED: "product/FETCH_PRODUCT_DETAILS_FAILED",
};
